development:
  adapter: postgresql
  encoding: unicode
  database: angular_devise_development
  host: localhost
  pool: 5
  username: postgres
  password: ap1194

test:
  adapter: postgresql
  encoding: unicode
  database: angular_devise_test
  host: localhost
  pool: 5
  username: postgres
  password: ap1194
